COUNTRIES = [
    {
        "name": "Japan",
        "official_name": "Japan",
        "capital": "Tokyo",
        "region": "Asia",
        "subregion": "East Asia",
        "population": "125.8 million",
        "currency": "Japanese Yen (JPY)",
        "language": "Japanese",
        "timezone": "UTC+9",
        "flag": "🇯🇵",
        "description": "Japan combines modern cities, historic temples, and deep cultural traditions with efficient public transport and strong safety standards.",
        "best_time": "March to May and October to November",
        "highlights": ["Mount Fuji", "Kyoto temples", "Tokyo food culture", "Hokkaido nature"],
        "visa_note": "Visa-free or easy eVisa access for many nationalities.",
        "safety": "Very safe",
        "climate": "Temperate",
    },
    {
        "name": "France",
        "official_name": "French Republic",
        "capital": "Paris",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": "68.4 million",
        "currency": "Euro (EUR)",
        "language": "French",
        "timezone": "UTC+1",
        "flag": "🇫🇷",
        "description": "France is known for art, architecture, food, history, and easy access to high-speed rail and major European gateways.",
        "best_time": "April to June and September to October",
        "highlights": ["Eiffel Tower", "Louvre Museum", "French Riviera", "Bordeaux wine regions"],
        "visa_note": "Schengen visa rules may apply depending on your nationality.",
        "safety": "Generally safe",
        "climate": "Temperate",
    },
    {
        "name": "Canada",
        "official_name": "Canada",
        "capital": "Ottawa",
        "region": "North America",
        "subregion": "Northern America",
        "population": "40.1 million",
        "currency": "Canadian Dollar (CAD)",
        "language": "English and French",
        "timezone": "UTC-3 to UTC-8",
        "flag": "🇨🇦",
        "description": "Canada offers a strong quality of life, excellent public services, and superb natural scenery from mountains to coastlines.",
        "best_time": "June to September",
        "highlights": ["Banff", "Toronto", "Montreal", "Niagara Falls"],
        "visa_note": "Entry requirements vary by nationality and immigration route.",
        "safety": "Very safe",
        "climate": "Varied climate",
    },
    {
        "name": "Brazil",
        "official_name": "Federative Republic of Brazil",
        "capital": "Brasília",
        "region": "South America",
        "subregion": "Latin America",
        "population": "216.4 million",
        "currency": "Brazilian Real (BRL)",
        "language": "Portuguese",
        "timezone": "UTC-3",
        "flag": "🇧🇷",
        "description": "Brazil offers vibrant culture, major cities, beaches, rainforests, and varied regional experiences.",
        "best_time": "May to October",
        "highlights": ["Rio de Janeiro", "Amazon rainforest", "Salvador", "Iguazu Falls"],
        "visa_note": "Entry requirements vary depending on your passport and travel purpose.",
        "safety": "Moderate; caution in large cities",
        "climate": "Tropical",
    },
    {
        "name": "Kenya",
        "official_name": "Republic of Kenya",
        "capital": "Nairobi",
        "region": "Africa",
        "subregion": "East Africa",
        "population": "55.1 million",
        "currency": "Kenyan Shilling (KES)",
        "language": "English and Swahili",
        "timezone": "UTC+3",
        "flag": "🇰🇪",
        "description": "Kenya is a top destination for safari experiences, university opportunities, and business travel in East Africa.",
        "best_time": "June to October and January to February",
        "highlights": ["Maasai Mara", "Mount Kenya", "Nairobi", "Diani Beach"],
        "visa_note": "Many travelers need a visa before entering the country.",
        "safety": "Moderate; local advice is recommended",
        "climate": "Warm and tropical",
    },
    {
        "name": "Australia",
        "official_name": "Commonwealth of Australia",
        "capital": "Canberra",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": "26.7 million",
        "currency": "Australian Dollar (AUD)",
        "language": "English",
        "timezone": "UTC+8 to UTC+10",
        "flag": "🇦🇺",
        "description": "Australia is known for beaches, wildlife, strong university systems, and a high standard of living in major cities.",
        "best_time": "September to November and March to May",
        "highlights": ["Sydney Opera House", "Great Barrier Reef", "Uluru", "Melbourne"],
        "visa_note": "Visa status depends on your nationality and program type.",
        "safety": "Very safe",
        "climate": "Mostly temperate",
    },
]

COUNTRY_LOOKUP = {country["name"].lower(): country for country in COUNTRIES}


def get_country(country_name):
    if not country_name:
        return None
    return COUNTRY_LOOKUP.get(country_name.strip().lower())


def list_countries():
    return [country["name"] for country in COUNTRIES]
